py_library(
    name = "queries",
    srcs = [
        "hardware_query.py",
        "cpu_query.py",
        "gpu_query.py",
        "ram_query.py",
        "sensors_query.py",
        ],
    deps = [
    ],
    imports = ["../../venv"],
    visibility = ["//visibility:public"],
)