py_library(
    name = "utils",
    srcs = [
        "search_utils.py",
        "log_utils.py",
        "dataframe_to_bokeh_utils.py",
        ],
    imports = ["../../venv"],
    deps = [],
    visibility = ["//visibility:public"],
)