py_test (
    name = "hardware_query_tests",
    srcs = ["hardware_query_tests.py"],
    deps = [
        "//src/backend:queries",
    ],
)

py_test (
    name = "hardware_query_write_to_file_tests",
    srcs = ["hardware_query_write_to_file_tests.py"],
    deps = [
        "//src/backend:queries",
    ],
    imports = [
        "tests/backend/logs"
    ]
)
