name: UI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: docker://brucknem/bazel-base:latest
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install frontend
        run: pip install --no-cache-dir --upgrade -r src/frontend/requirements.txt

      # Runs the bazel tests
      - name: Bazel tests
        run: bazel run //tests/frontend:ui_tests

